create sequence hibernate_sequence start with 3 increment by 1;
create table film (id bigint not null, filename varchar(255), title varchar(2147483647), genre varchar(2147483647), year varchar, user_id bigint, primary key (id));
create table user_role (user_id bigint not null, roles varchar(255));
create table usr (id bigint generated by default as identity, active boolean not null, email varchar(255), password varchar(255), username varchar(255), primary key (id));
alter table film add constraint message_user_fk foreign key (user_id) references usr;
alter table user_role add constraint user_role_user_fk foreign key (user_id) references usr